# -*- coding: utf-8 -*-
"""midsemprac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lxYbAst4abBv0Gb_QJJCT8C7z53f3Z-O
"""

#roll div batch prn
#problem statement
#csv file
#code
#output

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/astrologysciencetist.csv')
print(data)

#asending
data.sort_values(by=['Name'])

#desending
data.sort_values(by=['Name'],ascending=False)

#dump in form of dictionary
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/astrologysciencetist.csv')
data_dict = data.to_dict(orient='records')
print(data_dict)

#Use lambda for marking out female percentage
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/astrologysciencetist.csv')
Gender = 'Gender'
female_percentage = (data['Gender'].apply(lambda x: 1 if x == 'female' else 0).sum() / len(data['Gender'])) * 100
print("Female Percentage in", Gender, ":", female_percentage)